version: 2.1

orbs:
  python: tinyclues/python@3.1.0

jobs:
  python-36:
    working_directory: ~/fletcher-circleci
    docker:
      # We use our own Python, so the version here is not relevant
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          command: ./ci/circle_build_linux.sh 3.6
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
  python-37:
    working_directory: ~/fletcher-circleci
    docker:
      # We use our own Python, so the version here is not relevant
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          command: ./ci/circle_build_linux.sh 3.7
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
  upstream-dev:
    working_directory: ~/fletcher-circleci
    docker:
      # We use our own Python, so the version here is not relevant
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          command: ./ci/circle_build_linux.sh 3.6 1
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  build:
    jobs:
      - python-36
      - python-37
      - python/conda_build:
          name: build_package
      - python/conda_deploy:
          name: package_deploy
          context: artifactory
          requires:
            - python-36
            - python-37
            - build_package
